### DISCUSSION TITLE
[Ingress] minikube addons enable ingress 失败

### DISCUSSION THREAD

**Discussion by 916980name** [guangzhengli/kubenates_workshop#91] [General]
```
$ minikube addons enable ingress
💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
    ▪ Using image registry.k8s.io/ingress-nginx/controller:v1.7.0
    ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
    ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
🔎  Verifying ingress addon...

❌  Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_addons_4e79cb121815fc130446243219e97fe20a361239_0.log                  │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```
我看有人说还是gcr的问题，但是有个一句话解决方案，不知道有没有同样问题的，希望能节省你的时间：
https://github.com/kubernetes/minikube/issues/10544#issuecomment-950252247

此时可以通过`minikube ip`的IP来访问，如`http://192.168.49.2/`  
但是
### 想要给本地网络提供服务
尝试
```
$ kubectl port-forward ingress-nginx-controller-648cf4cd7d-dqb4j -n ingress-nginx --address 0.0.0.0 80:80
Unable to listen on port 80: Listeners failed to create with the following errors: [unable to create listener: Error listen tcp4 0.0.0.0:80: bind: permission denied]
error: unable to listen on any of the requested ports: [{80 80}]
```
加`sudo`
```
$ sudo kubectl port-forward ingress-nginx-controller-648cf4cd7d-dqb4j -n ingress-nginx --address 0.0.0.0 80:80
[sudo] password for xxxx: 
E0719 20:31:56.578262  850892 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0719 20:31:56.578542  850892 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0719 20:31:56.579715  850892 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0719 20:31:56.580944  850892 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
行80不给用是吧，换个高位端口成功：
```
kubectl port-forward ingress-nginx-controller-648cf4cd7d-dqb4j -n ingress-nginx --address 0.0.0.0 18080:80
```
此时可以通过本地网卡的IP来访问，有线无线回环皆可，如`http://192.168.0.200:18080/hello`  
但是，我今天非要用上80
### 非要用上80端口
![image](https://github.com/guangzhengli/k8s-tutorials/assets/92700513/9fbc431e-4d0b-4e95-8310-6fe7f7232b0f)
前面加个nginx吧
```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
              proxy_redirect off;
              proxy_pass http://172.17.0.1:18080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_read_timeout 36000s;

    }
}
```
curl一下
```
$ curl http://192.168.0.200/hello
[v3] Hello, Kubernetes!, From host: hellok8s-deployment-75f68fb95d-xkb6m
```
舒服了

**Comment by 916980name** [comment]
### 如果通过ingress访问前后端分离项目
前端react+nginx docker，后端java+jdk docker  
那么可能会产生如下ingress配置
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-ingress
  namespace: qa
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-clusterip
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-clusterip
                port:
                  number: 80
```
如果是想要通过path rewrite进行分离的项目，写成这样，这个rewrite也会影响frontend。
导致前端请求被重写成`/`，表现为页面请求全200， 但是返回的都是同样的结果(index.html)，白屏。
在一度怀疑了前端项目的各种配置不限于`react-router`，`package.json hompage`，`webpack`之后   
中间改成这样
```
...
...
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      rewrite /api/(.+)$ /$1 break;
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
...
...
```
